apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: openshift-sandboxed-containers-operator
data:
  #CLOUD_PROVIDER: "libvirt"
  #LIBVIRT_NET: "default
  #LIBVIRT_POOL: "default"
  #LIBVIRT_VOL_NAME: "default"
  #LIBVIRT_DIR_NAME: "/var/lib/libvirt/images/"
